config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  namespace :admin do
    root 'home#index'
    resources :users, only: [:index, :update]
    resources :feature_definitions
    resources :features
  end

  resources :profiles, only: [:show, :edit, :update]

  resources :albums, only: [:index, :destroy] do
    post :share, on: :collection
  end
   get 'awesome', to: 'home#awesome', as: 'awesome'
 get 'cost', to: 'home#cost', as: 'cost'
 get 'about', to: 'home#about', as: 'about'
 get 'contact', to: 'messages#new', as: 'new_message'
 post 'contact', to: 'messages#create', as: 'create_message'

  resources :features, only: [:index, :show] do
    member do
      post :enable
      post :disable
      post :reenable
    end
  end
  resource :customer, only: [:show, :edit, :update, :destroy]

  get '/dropbox_authorize' => 'dropbox#authorize', as: 'dropbox_authorize'
  get '/dropbox_unauthorize' => 'dropbox#unauthorize', as: 'dropbox_unauthorize'
  get '/dropbox_callback' => 'dropbox#dropbox_callback', as: 'dropbox_callback'

  get '/album_select' => 'albums#album_select', as: 'album_select'

  get '/google_drive_authorize' => 'google_drive#authorize', as: 'google_drive_authorize'
  get '/google_drive_unauthorize' => 'google_drive#unauthorize', as: 'google_drive_unauthorize'
  get '/google_drive_callback' => 'google_drive#google_drive_callback', as: 'google_drive_callback'

  root 'home#index'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def show
    load_user(:show_profile)
    @features = Feature.all
    @enabled_feature_identifiers = current_user&.enabled_feature_identifiers || []
  end

  def edit
    load_user(:update)
  end

  def update
    load_user(:update)
    if @user.update(user_params)
      flash.now[:notice] = "Changes saved!"
      redirect_to profile_path(@user) and return
    end
    render :show
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :company_name, :contact_email, :bio)
  end

  private

  def load_user(for_action)
    @user = User.find(params[:id])
    authorize! for_action, @user
  end


end

app/views/profiles/_features.html.erb
<h2>Features</h2>

<% if @enabled_feature_identifiers.length %>
  <h3>Enabled Features</h3>
  <p>You currently have the following features enabled:</p>
  <ul>
    <% @features.each do |feature| %>
      <% if @enabled_feature_identifiers.include?(feature.identifier) %>
        <li><%= feature.name %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>

<% if @enabled_feature_identifiers.length < @features.length %>
  <h3> More Features</h3>
  <p>There are more features you can add! <%= link_to "Check them out!", features_path %></p>

  <ul>
    <% @features.each do |feature| %>
      <% unless @enabled_feature_identifiers.include?(feature.identifier) %>
        <li><%= feature.name %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/profiles/edit.html.erb
<section id="profileEdit" class="container">
  <h1>Edit Profile</h1>

  <div class="row dataFields">
    <div class="col-sm-12">
      <%= bootstrap_form_for @user, url: profile_path(@user) do |f| %>

      <%= f.text_field :first_name %>
      <%= f.text_field :last_name %>
      <%= f.text_field :company_name %>
      <%= f.text_field :contact_email %>
      <%= f.text_area :bio, rows: 5 %>

      <%= f.submit "Save" %>
      <% end %>
    </div>
  </div>
</section>

app/views/profiles/show.html.erb
<section id="profileView" class="container">
  <div class="row">
    <h1>
      <%= @user.full_name %>
      <% if @user.company_name.present? %>
        (<%= @user.company_name %>)
      <% end %>
    </h1>
    <% if can? :update, @user %>
      <button class="pull-right"><%= link_to 'Edit Profile', edit_profile_path(@user) %></button>
    <% end %>
  </div>
  <div class="row profileCloudOptions">
    <div class="col-md-6 col-xs-12">
      <% if current_user.google_token.blank? %>
        <i class="fae-google-drive"></i> <p><%= link_to "Connect Google Storage Account", google_drive_authorize_path %></p>
      <% else %>
        <i class="fae-google-drive"></i> <p>Google Drive Account Connected</p>
      <% end %>
    </div>
    <div class="col-md-6 col-xs-12">
      <% if current_user.dropbox_session.blank? %>
        <i class="fa fa-dropbox" aria-hidden="true"></i>  <p><%= link_to "Connect Dropbox Storage Account", dropbox_authorize_path %></p>
      <% else %>
        <i class="fa fa-dropbox" aria-hidden="true"></i>  <p>Dropbox Account Connected</p>
      <% end %>
    </div>
  </div>

  <div class="dataFields">
    <div class="profileLabel col-md-3 col-xs-12">
      First Name
    </div>
    <div class="col-md-9 col-xs-12">
      <%= present(@user.first_name, '-') %>
    </div>
    
    <div class="profileLabel col-md-3 col-xs-12">
      Last Name
    </div>
    <div class="col-md-9 col-xs-12">
      <%= present(@user.last_name, '-') %>
    </div>

    <div class="profileLabel col-md-3 col-xs-12">
      Company Name
    </div>
    <div class="col-md-9 col-xs-12">
      <%= present(@user.company_name, '-') %>
    </div>

    <div class="profileLabel col-md-3 col-xs-12">
      Email Address:
    </div>
    <div class="col-md-9 col-xs-12">
      <%= present(@user.email, '-') %>
    </div>

    <div class="profileLabel col-md-3 col-xs-12">
      Bio:
    </div>
    <div class="col-md-9 col-xs-12">
      <blockquote>
        <%= simple_format(present(@user.bio,'Bio not completed')) %>
      </blockquote>
    </div>

    <span class="clearfix"></span>
  </div>

  <% if current_user == @user %>
    <%= render 'features' %>
  <% end %>
</section>