config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  namespace :admin do
    root 'home#index'
    resources :users, only: [:index, :update]
    resources :feature_definitions
    resources :features
  end

  resources :profiles, only: [:show, :edit, :update]

  resources :albums, only: [:index, :destroy] do
    post :share, on: :collection
  end
   get 'awesome', to: 'home#awesome', as: 'awesome'
 get 'cost', to: 'home#cost', as: 'cost'
 get 'about', to: 'home#about', as: 'about'
 get 'contact', to: 'messages#new', as: 'new_message'
 post 'contact', to: 'messages#create', as: 'create_message'

  resources :features, only: [:index, :show] do
    member do
      post :enable
      post :disable
      post :reenable
    end
  end
  resource :customer, only: [:show, :edit, :update, :destroy]

  get '/dropbox_authorize' => 'dropbox#authorize', as: 'dropbox_authorize'
  get '/dropbox_unauthorize' => 'dropbox#unauthorize', as: 'dropbox_unauthorize'
  get '/dropbox_callback' => 'dropbox#dropbox_callback', as: 'dropbox_callback'

  get '/album_select' => 'albums#album_select', as: 'album_select'

  get '/google_drive_authorize' => 'google_drive#authorize', as: 'google_drive_authorize'
  get '/google_drive_unauthorize' => 'google_drive#unauthorize', as: 'google_drive_unauthorize'
  get '/google_drive_callback' => 'google_drive#google_drive_callback', as: 'google_drive_callback'

  root 'home#index'
end

app/models/feature_definition.rb
class FeatureDefinition < ApplicationRecord
  belongs_to :feature

  def to_billable_feature_data
    {
      feature_identifier: feature.identifier, 
      display_name: name, 
      price_per_day: price_per_day, 
      activation_price: addition_price
    }
  end
end

app/controllers/admin/feature_definitions_controller.rb
module Admin
  class FeatureDefinitionsController < ApplicationAdminController
    before_action :load_definitions, only: :index
    load_and_authorize_resource
    
    def index
    end
    
    def show
    end

    def new
    end

    def create
      respond_to do |format|
        if @feature_definition.save
          format.html { redirect_to [:admin, @feature_definition], notice: 'Feature Definition was successfully created.' }
          format.json { render :show, status: :created, location: [:admin, @feature_definition] }
        else
          format.html { render :new }
          format.json { render json: @feature_definition.errors, status: :unprocessable_entity }
        end
      end
    end

    def edit
    end

    def update
      respond_to do |format|
        if @feature_definition.update(feature_definition_params)
          format.html { redirect_to [:admin, @feature_definition], notice: 'Feature Definition was successfully updated.' }
          format.json { render :show, status: :ok, location: [:admin, @feature_definition] }
        else
          format.html { render :edit }
          format.json { render json: @feature_definition.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @feature_definition.destroy
      respond_to do |format|
        format.html { redirect_to admin_feature_definitions_url, notice: 'Feature Definition was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def load_definitions
      @feature_definitions = FeatureDefinition.accessible_by(current_ability).includes(:feature).joins(:feature).order('features.name asc')
    end

    def feature_definition_params
      params.require(:feature_definition).permit(:name, :feature_id, :price_per_day, :addition_price)
    end

  end
end

app/views/admin/feature_definitions/_form.html.erb
<%= form_for [:admin,@feature_definition], :html => { :class => "form-horizontal feature_definition" } do |f| %>

  <% if @feature_definition.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@feature_definition.errors.count, "error") %> prohibited this feature definition from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @feature_definition.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <%= f.label :feature, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select :feature_id, Feature.all, :id, :identifier, {prompt: true}, {:class => 'form-control'} %>
    </div>
    <%=f.error_span(:feature) %>
  </div>

  <div class="form-group">
    <%= f.label :price_per_day, 'Price Per Day (m¢)', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price_per_day, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price_per_day) %>
  </div>

  <div class="form-group">
    <%= f.label :addition_price, 'Addition Price (m¢)', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :addition_price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:addition_price) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', admin_feature_definitions_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/admin/feature_definitions/edit.html.erb
<div class="page-header">
  <h1>Edit Feature Definition</h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/feature_definitions/index.html.erb
<div class="page-header">
  <h1>Feature Definitions</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Feature</th>
      <th>Price Per Day</th>
      <th>Addition Price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @feature_definitions.each do |feature_definition| %>
      <tr>
        <td><%= link_to feature_definition.name, 
                        admin_feature_definition_path(feature_definition) %>
        </td>
        <td><%= feature_definition.feature.identifier %></td>
        <td><%= feature_definition.price_per_day %> m¢ (<%= number_to_currency(millicents_to_dollars(feature_definition.price_per_day), precision: 6 ) %>)</td>
        <td><%= feature_definition.addition_price %> m¢ (<%= number_to_currency(millicents_to_dollars(feature_definition.addition_price), precision: 6 ) %>)</td>
        <td>
          <%= link_to 'Show',
                      admin_feature_definition_path(feature_definition), 
                      :class => 'btn btn-default btn-xs' %>
          <%= link_to 'Edit',
                      edit_admin_feature_definition_path(feature_definition), 
                      :class => 'btn btn-default btn-xs' %>
          <%= link_to 'Destroy',
                      admin_feature_definition_path(feature_definition),
                      :method => :delete,
                      :data => { :confirm => 'Are you sure?' },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Feature Definition',
            new_admin_feature_definition_path,
            :class => 'btn btn-primary' %>

app/views/admin/feature_definitions/new.html.erb
<div class="page-header">
  <h1>New Feature Definition</h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/feature_definitions/show.html.erb
<div class="page-header">
  <h1>Feature Definition</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Name:</strong></dt>
  <dd><%= @feature_definition.name %></dd>
  <dt><strong>Feature Identifier:</strong></dt>
  <dd><%= @feature_definition.feature.identifier %></dd>
  <dt><strong>Price Per Day (m¢):</strong></dt>
  <dd><%= @feature_definition.price_per_day %> (<%= number_to_currency(millicents_to_dollars(@feature_definition.price_per_day), precision: 6 ) %>)</dd>
  <dt><strong>Addition Price (m¢):</strong></dt>
  <dd><%= @feature_definition.addition_price %> (<%= number_to_currency(millicents_to_dollars(@feature_definition.addition_price), precision: 6 ) %>)</dd>
</dl>

<%= link_to 'Back',
            admin_feature_definitions_path, 
            :class => 'btn btn-default'  %>
<%= link_to 'Edit',
              edit_admin_feature_definition_path(@feature_definition),
              :class => 'btn btn-default' %>
<%= link_to 'Destroy',
              admin_feature_definition_path(@feature_definition),
              :method => 'delete',
              :data => { :confirm => 'Are you sure?' },
              :class => 'btn btn-danger' %>