config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  namespace :admin do
    root 'home#index'
    resources :users, only: [:index, :update]
    resources :feature_definitions
    resources :features
  end

  resources :profiles, only: [:show, :edit, :update]

  resources :albums, only: [:index, :destroy] do
    post :share, on: :collection
  end
   get 'awesome', to: 'home#awesome', as: 'awesome'
 get 'cost', to: 'home#cost', as: 'cost'
 get 'about', to: 'home#about', as: 'about'
 get 'contact', to: 'messages#new', as: 'new_message'
 post 'contact', to: 'messages#create', as: 'create_message'

  resources :features, only: [:index, :show] do
    member do
      post :enable
      post :disable
      post :reenable
    end
  end
  resource :customer, only: [:show, :edit, :update, :destroy]

  get '/dropbox_authorize' => 'dropbox#authorize', as: 'dropbox_authorize'
  get '/dropbox_unauthorize' => 'dropbox#unauthorize', as: 'dropbox_unauthorize'
  get '/dropbox_callback' => 'dropbox#dropbox_callback', as: 'dropbox_callback'

  get '/album_select' => 'albums#album_select', as: 'album_select'

  get '/google_drive_authorize' => 'google_drive#authorize', as: 'google_drive_authorize'
  get '/google_drive_unauthorize' => 'google_drive#unauthorize', as: 'google_drive_unauthorize'
  get '/google_drive_callback' => 'google_drive#google_drive_callback', as: 'google_drive_callback'

  root 'home#index'
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container-fluid">
    <div class="row">
      <div class='col-xs-12 col-lg-6'>

        <!-- Start Newsletter Signup -->
        <div class='sm-marketing-footer-newsletter-form'>

          <form id='sm-marketing-footer-newsletter-form' class='col-xs-12 pull-left'>

            <h6 class="newsletter">Sign up for our newsletter</h6>

            <div class='sm-marketing-newsletter-input-group sm-flex'>
              <input name='email' type='text' class='sm-marketing-field-text-input' placeholder='Enter email address' value='' />
              <button type='submit' class='sm-marketing-button sm-marketing-button-dark-gray' disabled>
                <span class='sm-marketing-newsletter-button-text'>
                  Sign Up
                </span>
                <span class='sm-progress-spinner'></span>
              </button>
            </div>

            <div class='sm-marketing-newsletter-success'>
              Thank you! Keep an eye on your inbox for exciting&nbsp;announcements.
            </div>


          </form>
        </div>
        <!-- End Newsletter Signup -->

        <!-- Start Footer Social Links -->
        <div class='sm-marketing-footer-social'>
          <ul class='social'>
            <li>
              <a  href="http://www.facebook.com/" target="_blank" >
                <i class="fa fa-facebook-official" aria-hidden="true"></i>
              </a>
            </li>
            <li>
              <a  href="http://twitter.com/">
              </a>
              <i class="fa fa-twitter" aria-hidden="true"></i>
            </li>
            <li>
              <a  href="http://www.instagram.com/" target="_blank" >
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
            </li>
            <li>
              <a  href="http://www.youtube.com/" target="_blank" >
                <i class="fa fa-youtube" aria-hidden="true"></i>
              </a>
            </li>

          </ul>
        </div>

        <div class="col-xs-12">
          <div class="canada">
            <i class="icon-canada" id="flag">
            </i>
            <small>product of canada</small>
          </div>
        </div>

      </div>

      <div class='col-xs-12 col-lg-6 footer-navigation'>
    <!--    <div class='col-xs-2'>
          <h6>
            Apps
          </h6>
          <nav>
            <ul class='sm-marketing-footer-links'>
              <li>
                <a class="sm-link-tracking" href="https://itunes.apple.com/us/app//id364894061?mt=8" target="_blank" data-link-tracking-category="Marketing Page" data-link-tracking-action="Navigation Click" data-link-tracking-label="iOS" data-link-tracking-contexts="[{&quot;schema&quot;:&quot;iglu:com.\/screen\/jsonschema\/1-0-0&quot;,&quot;data&quot;:{&quot;section_name&quot;:&quot;Footer&quot;}}]">iOS</a>
              </li>
              <li>
                <a class="sm-link-tracking" href="https://play.google.com/store/apps/details?id=com.snapwood.smugfolio&hl=en" target="_blank" data-link-tracking-category="Marketing Page" data-link-tracking-action="Navigation Click" data-link-tracking-label="Android" data-link-tracking-contexts="[{&quot;schema&quot;:&quot;iglu:com.\/screen\/jsonschema\/1-0-0&quot;,&quot;data&quot;:{&quot;section_name&quot;:&quot;Footer&quot;}}]">Android</a>
              </li>
              <li>
                <a class="sm-link-tracking" href="http://help..com/customer/portal/articles/1491124-how-do-i-upload-from-lightroom" target="_blank" data-link-tracking-category="Marketing Page" data-link-tracking-action="Navigation Click" data-link-tracking-label="Lightroom" data-link-tracking-contexts="[{&quot;schema&quot;:&quot;iglu:com.\/screen\/jsonschema\/1-0-0&quot;,&quot;data&quot;:{&quot;section_name&quot;:&quot;Footer&quot;}}]">Lightroom</a>
              </li>
            </ul>
          </nav>
        </div>
-->
        <div class='col-xs-3'>
          <h6>
            Community
          </h6>
          <nav>
            <ul class='sm-marketing-footer-links'>
<!--
              <li>
                <a class="sm-link-tracking" href="http://news..com" target="_blank" data-link-tracking-category="Marketing Page" data-link-tracking-action="Navigation Click" data-link-tracking-label="Blog" data-link-tracking-contexts="[{&quot;schema&quot;:&quot;iglu:com.\/screen\/jsonschema\/1-0-0&quot;,&quot;data&quot;:{&quot;section_name&quot;:&quot;Footer&quot;}}]">Blog</a>
              </li>
              <li>
                <a class="sm-link-tracking" href="/about/events" data-link-tracking-category="Marketing Page" data-link-tracking-action="Navigation Click" data-link-tracking-label="Events" data-link-tracking-contexts="[{&quot;schema&quot;:&quot;iglu:com.\/screen\/jsonschema\/1-0-0&quot;,&quot;data&quot;:{&quot;section_name&quot;:&quot;Footer&quot;}}]">Events</a>
              </li>
-->
              <li>
                <a class="sm-link-tracking" href="http://dgrin.com" target="_blank" data-link-tracking-category="Marketing Page" data-link-tracking-action="Navigation Click" data-link-tracking-label="Forum" data-link-tracking-contexts="[{&quot;schema&quot;:&quot;iglu:com.\/screen\/jsonschema\/1-0-0&quot;,&quot;data&quot;:{&quot;section_name&quot;:&quot;Footer&quot;}}]">Forum</a>
              </li>
            </ul>
          </nav>
        </div>            <!-- End Footer Nav Column Community -->

        <!-- Start Footer Nav Column Company -->

        <div class='col-xs-3'>
          <h6>
            Company
          </h6>
          <nav>
            <ul class='sm-marketing-footer-links'>
              <li>
                <a class="sm-link-tracking" href="/about">About</a>
              </li>
              <li>
                <a class="sm-link-tracking" href="/jobs" >Jobs</a>
              </li>
              <li>
                <a class="sm-link-tracking" href="/reseller">Partner Program</a>
              </li>
            <li><a  class="sm-link-tracking" href="/awesome">What makes us awesome?</a></li>

            </ul>
          </nav>
        </div>

        <div class='col-xs-3'>
          <h6>
            Product
          </h6>
          <nav>
            <ul class='sm-marketing-footer-links'>

<!--
              <li>
                <a class="sm-link-tracking" href="/stories/brent-gilmore" data-link-tracking-category="Marketing Page" data-link-tracking-action="Navigation Click" data-link-tracking-label="Stories" data-link-tracking-contexts="[{&quot;schema&quot;:&quot;iglu:com.\/screen\/jsonschema\/1-0-0&quot;,&quot;data&quot;:{&quot;section_name&quot;:&quot;Footer&quot;}}]">Stories</a>
              </li>
              <li>
                <a class="sm-link-tracking" href="/features/photo-website" data-link-tracking-category="Marketing Page" data-link-tracking-action="Navigation Click" data-link-tracking-label="Features" data-link-tracking-contexts="[{&quot;schema&quot;:&quot;iglu:com.\/screen\/jsonschema\/1-0-0&quot;,&quot;data&quot;:{&quot;section_name&quot;:&quot;Footer&quot;}}]">Features</a>
              </li>
            -->
              <li>
                <a class="sm-link-tracking" href="/plans">Cost</a>
              </li>

            </ul>
          </nav>
        </div>            <!-- End Footer Nav Column Product -->

        <!-- Start Footer Nav Column Support -->

        <div class='col-xs-3'>
          <h6>
            Support
          </h6>
          <nav>
            <ul class='sm-marketing-footer-links'>
              <li>
                <a class="sm-link-tracking" href="/forum" >Support Forum</a>
               </li>
                <li>
                  <a class="sm-link-tracking" href="/help">Call for help!</a>
                               </li>
                  <li>
                    <a class="sm-link-tracking" href="/feedback" >Feedback</a>
                        </li>
<!--
                    <li>
                      <a class="sm-link-tracking" href="/tutorials">Video Tutorials</a>
                    </li>
                  -->
                    <li>
                      <a class="sm-link-tracking" href="/about/terms" target="_blank">Terms</a>
                    </li>
                    <li>
                      <a class="sm-link-tracking" href="/about/privacy">Privacy</a>
                    </li>
                  </ul>
                </nav>
              </div>            <!-- End Footer Nav Column Support -->


              <!-- End Footer Navigation -->
            </div>
          </div>



          <div class="row bottom-footer">
            <div class="col-xs-4 trademark">
              <a href="http://www.altama.ca"><%= Date.today.year %> Altama Systems Inc.</a>
            </div>
            <div class="col-xs-4 bottommost-nav">
              <span>
                London, Ontario, Canada
              </span>
              <span>
                (778) 801-7936
              </span>
              <a href="#">
                Employee Login
              </a>
              <a href="#">
                Sitemap
              </a>
              <a href="#">
                Release Log
              </a>
            </div>
            <div class="col-xs-4 pull-right quote">
              <h3>Share your knowledge, it’s a way to achieve immortality.<br>
                <span class="light">~ Dalai Lama</span></h3>
              </div>
            </div>
          </div>
        </footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: 'navbar-brand' do %>
          <img alt="brand" src="<%= image_path('logo-400px.png') %>">Albumshare
        <% end %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a class="" href="/about">About</a></li>
          <li><a class="" href="/">Example Album</a></li>
          <li><a class="" href="/cost">Cost</a></li>
            <li><a class="" href="/awesome">What makes us awesome?</a></li>
          <li><a class="" href="/contact">Contact</a></li>
          <% if current_user&.is_admin %>
            <li><%= link_to "ADMIN", admin_root_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Hello, #{current_user.email}", profile_path(current_user) %></li>

            <% if current_user.dropbox_session.blank? && current_user.google_oauth2_uid.blank? %>
            <li><%= link_to "Connect Cloud Storage", dropbox_authorize_path %></li>
            <% end%>

            <!--<% if current_user.google_oauth2_uid.blank? %>-->
              <!--<li><%= link_to "Connect Google Account", user_google_oauth2_omniauth_authorize_path %></li>-->
            <!--<% end %>-->
            <% if current_user.google_token.blank? %>
              <li><%= link_to "Connect Google Account", google_drive_authorize_path %></li>
            <% end %>

            <% if !current_user.google_token.blank? | !current_user.dropbox_session.blank? %>
              <li><%= link_to "Albums", albums_path %></li>
            <% end %>

            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: '' %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path, class: 'login' %></li>
            <li><%= link_to "Share Photos", new_user_registration_path, class: 'register' %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/album_preview.js.erb
$("#album-preview").html("<%= escape_javascript(yield) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Albumshare - Share your Dropbox &amp; Drive photos with privacy.</title>
    <%= csrf_meta_tags %>
    <script src="https://use.fontawesome.com/645896d9c5.js"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <link rel="shortcut icon" href="<%= image_path('logo-400px.png') %>" type="image/x-icon">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => ENV['STRIPE_PUBLISHABLE_KEY'] %>
    <%= yield(:custom_css) %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield(:custom_header) %>
    
    <% if notice.present? %><p class="alert notice"><%= notice %></p><% end %>
    <% if alert.present? %><p class="alert"><%= alert %></p><% end %>
    
    <%= yield %>
    
    <%= render 'layouts/footer' %>
  </body>

</html>

app/views/layouts/marketing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Albumshare - Share your Dropbox &amp; Drive photos with privacy</title>
    <%= csrf_meta_tags %>
    <script src="https://use.fontawesome.com/645896d9c5.js"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <link rel="shortcut icon" href="<%= image_path('logo-400px.png') %>" type="image/x-icon">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <section id="album-container">
      <div id="banners">
        <% if notice.present? %><p class="alert notice"><%= notice %></p><% end %>
        <% if alert.present? %><p class="alert"><%= alert %></p><% end %>
      </div>
      <%= yield %>
    </section>
    <%= render 'layouts/footer' %>

    <script src="http://masonry.desandro.com/masonry.pkgd.js"></script>
    <script src="http://imagesloaded.desandro.com/imagesloaded.pkgd.js"></script>
  </body>
</html>